### ISSUE TITLE
Integrate browser tabs and controls

### ISSUE THREAD

**Issue by robmoorman** [nos/client#101]
While surfing the nOS web, it would be nice to have an option to add multiple tabs, just like Chrome

<img width="801" alt="screen shot 2018-04-24 at 22 35 05" src="https://user-images.githubusercontent.com/529396/39212713-d2492d70-480f-11e8-9c82-e8a4e49bf4fa.png">

**Comment by mhuggins** [comment]
Thanks for adding this!  This is something we intend to add, however we want to wait until we complete some effort with regards to looking into muon.
