### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by sacharya** [nos/client#102]
\# yarn start --debug
yarn start v0.27.5
$ concurrently -r "yarn run start-react" "wait-on http://localhost:3000/ && yarn run start-electron" --kill-others --success first
Starting the development server... /root/nos-client/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory error Command failed with exit code 127. error Command failed with exit code 1.

My Environment:
\# uname -a
Linux nos-dapp 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mhuggins** [comment]
According to [this StackOverflow answer](https://stackoverflow.com/a/38935092/107277), you need to `apt-get install libgtk2.0-0`.

**Comment by jeez07z** [comment]
Environment: Running Ubuntu 14.04 VM on Windows 10

Had to install these
apt-get install libgtk2.0-0
apt-get install libx11-xcb-dev
apt-get install libxtst6
apt-get install libxss1
apt-get install libgconf-2-4

Below failed:
sudo apt install libgtk2.0-0:i386

**Comment by DalderupMaurice** [comment]
What error does it give? 
Looking further into the issue I came across these 2 resources, maybe these might point to a right direction:
https://stackoverflow.com/questions/38935024/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0
https://electronjs.org/docs/development/build-instructions-linux

**Comment by mhuggins** [comment]
@sacharya Any updates from @DalderupMaurice's suggestions?

**Comment by DalderupMaurice** [comment]
Closing as there's no feedback - feel free to reopen/comment when needed
