### ISSUE TITLE
Incorrect error messages shown

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#108]
## Expected Behavior
For example: 
When providing an invalid scriptHash with `testInvoke` (or any other API function)
There should be an error saying `Invalid script hash: "${scriptHash}"` (Which is thrown in the `makeTestInvokeActions` when validating the scriptHash)

This issue consists through every current action and should be fixed for every current action

## Current Behavior
When providing an invalid scriptHash with `testInvoke` (or any other API function)
There is an error saying `Invocation failed for operation "${props.operation}" on "${props.scriptHash}"` 

## Possible Solution
Catching the correct error thrown in the actions (in this case the `makeTestInvokeActions` which should be caught with `withRejectMessage` in `components -> browser -> RequestProcessor -> TestInvoke index.js`

## Steps to Reproduce (for bugs)
1. Execute nos.testInvoke('invaldScriptHash','xx',xx')
.then(res => console.log(res))
.catch(err => console.log(err));

--> err =  `Invocation failed for operation "${props.operation}" on "${props.scriptHash}"` 
err SHOULD be  `Invalid script hash: "${scriptHash}"`

## Context
It's currently not clear WHY `testInvoke` would fail because it gives a general error. With any error you get the same error message and developers won't know that their scriptHash is invalid

## Your Environment
* Version used: latest on dev/master
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): node, nvm LTS, yarn 1.6
* Operating System and version (desktop or mobile): MacOSX

**Comment by jeroenptrs** [comment]
Is this a problem relating to console.***'s being cut off after the first argument?

**Comment by DalderupMaurice** [comment]
No, currently thrown error's in ANY action are lost in deep space and a regular - common error message pops up, defined in `components -> browser -> RequestProcessor -> TestInvoke index.js`

**Comment by wjwater** [comment]
I'm looking at this issue, as a good first issue for me. So as I understand, changing the reject message text is just a part of the solution. As the text is displayed only in the browser console, and it would be better to show the message as a popup?

**Comment by DalderupMaurice** [comment]
I'll show an example :)  @wjwater 

In the action - `makeInvocationActions.js` in the `actions/dapps` folder you see this piece of code:
![](https://i.imgur.com/dOkch0T.png)

If a validation error occurs. Take for example the scriptHash is not a scriptHash, an error is thrown.

This error is CAUGHT in `\components\Browser\RequestsProcessor\Invoke` in the `index.js` file shown here on `line 46`:
![](https://i.imgur.com/RGpQgoV.png)

This seems alright, but the error message is hardcoded and the actually thrown error message (`throw new Error(`Invalid script hash: "${scriptHash}"`)` --> messsage: `Invalid script hash: "${scriptHash}'') is lost.

However, this exact message SHOULD be caught in  `\components\Browser\RequestsProcessor\Invoke` in the `index.js`  and replaced by the currently hardcoded error message.

This needs to be done for every action :P but with 1 having the solution would be a great start

**Comment by trueinsider** [comment]
If I understand correctly this is not easy to do and would require modification of spunky, because from what I see there is currently no way to propagate instance of Error to or catch it in `index.js`

**Comment by mhuggins** [comment]
The error is caught by spunky and can be exposed via withError (
https://github.com/neoverse/spunky/blob/master/README.md#witherror). We
have a withRejectMessage HOC that encapsulates this, but it will just need
to be updated to expose the error message.
