### ISSUE TITLE
Build confirm function wrapper for complex dialogs

### ISSUE THREAD

**Issue by mhuggins** [nos/client#118]
## Expected Behavior
The `confirm` redux action needs a wrapper to support more complex form dialogs.  It should support complex interactions (more than just a string for its `children`) as well as being able to pass a result as arguments to `onConfirm`.

## Current Behavior
The `confirm` redux action accept children string/node and an `onConfirm` callback that is not given any arguments.

## Possible Solution
🤔

## Steps to Reproduce (for bugs)
1. Checkout #109 & run client
2. Navigate to nOS settings
3. Click "Add custom network configuration"
4. Observe the complex dialog interaction

## Context
https://github.com/nos/client/pull/109#discussion_r184884800

## Your Environment
* Version used: all
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): all
* Operating System and version (desktop or mobile): all

**Comment by jeroenptrs** [comment]
I think this is a bit too complex for a `good first issue` tag, which is why I'm removing it.

**Comment by mhuggins** [comment]
An example of how this can be more encapsulated can be seen in #513, where it is wrapped in an `InvocationPrompt` component.  The same could be done for any modal in the future.
