### ISSUE TITLE
NEO/GAS & NEP-5 Token Wallet Tab

### ISSUE THREAD

**Issue by deanpress** [nos/client#12]
Requires all basic wallet functions:
* [x] View NEO/GAS Funds
* [x] Make NEO/GAS Transactions
* [x] View NEP-5 Funds
* [ ] Make NEP-5 Transactions

**Comment by jeroenptrs** [comment]
@DalderupMaurice @mhuggins I'm going to make this a `team issue`. Especially since this is a new window and seems a bit more complex than at first glance

**Comment by mhuggins** [comment]
@jeroenptrs Sounds good to me 👍

**Comment by DalderupMaurice** [comment]
This is related to my open PR #113 @jeroenptrs @mhuggins 
It's almost done 😂

**Comment by jeroenptrs** [comment]
Before we actually start transferring NEP-5 tokens, a great step in-between might be to start listing them? @DalderupMaurice @mhuggins @deanpress
