### ISSUE TITLE
Creating a production build (yarn dist) fails

### ISSUE THREAD

**Issue by jeroenptrs** [nos/client#120]
Getting a minifying error when compiling the source for a production build. This should be fixed in `react-scripts 2.0` and already has preliminary work done in branch `fix/buildingIssues`

## Expected Behavior
`yarn dist` creates a production build.

## Current Behavior
`yarn dist` fails (see screenshot)
![screenshot 2018-05-01 18 53 35](https://user-images.githubusercontent.com/19305608/39483284-25c8eb86-4d72-11e8-90be-43e5de8f7de7.png)

## Possible Solution
Update the `fix/buildingIssues` branch - rebase it to develop's HEAD - and fix whatever causes the tests to fail.

## Steps to Reproduce (for bugs)
1. Checkout develop
2. `yarn`
3. `yarn dist`

## Context
Creating a production build is critical for mass adoption.

## Your Environment
* Version used: develop branch @ latest commit
* Environment name and version: `node v8.11.0`, `npm 5.6.0`, `nvm 0.33.6`
* Operating System and version: macOS Sierra

**Comment by mhuggins** [comment]
I previously had a step in the build (in `package.json`) to `rm -rf node_modules/neon-js/src`.  Ideally this wouldn't be needed, and the latest in-progress version of create-react-app should solve packages that are not properly minified.

**Comment by ansrivas** [comment]
Indeed I tried to reproduce it, but couldn't. The prod-build works actually fine without any complains apart from linting errors.

```
OS: Fedora 27
Yarn: 1.6.0
node v8.0.0 
npm v5.0.0
```

Build logs:

```File sizes after gzip:

  485.56 KB  build/static/js/main.b5d183c3.js
  2.99 KB    build/static/css/main.ef79d2e2.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/CRA-deploy

Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
  • electron-builder version=19.56.0
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=dist/electron-builder.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=node-hid
  • packaging       platform=linux arch=x64 electron=1.8.2 appOutDir=dist/linux-unpacked
Downloading tmp-18358-1-SHASUMS256.txt-1.8.2
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
  • building        target=AppImage arch=x64 file=dist/nos-0.1.0-x86_64.AppImage
  • downloading     path=/home/asrivastava/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64 url=https://github.com/develar/app-builder/releases/download/v0.6.1/app-builder-v0.6.1-linux-x64.7z
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • downloading     path=/home/asrivastava/.cache/electron-builder/appimage/appimage-9.0.5 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.0.5/appimage-9.0.5.7z
  • building embedded block map file=dist/nos-0.1.0-x86_64.AppImage
Done in 155.09s.```

**Comment by jeroenptrs** [comment]
@mhuggins If I recall correctly it failed on my end even with the neon-js src removed (it just stopped at a different point). I think it has something to do with react-scripts v1 not supporting specific es6 functions but I could be wrong. I will try to replicate this tomorrow.

**Comment by jeroenptrs** [comment]
Upgrading this to team issue. Priority issue at the moment.

**Comment by mhuggins** [comment]
Pretty sure I've got a fix for this, just need to move it out of my working branch into its own branch/PR.  I'll push it up ASAP in the morning.
