### ISSUE TITLE
nOSLocal environment from the nOs client settings does not use Neo local environment

### ISSUE THREAD

**Issue by boreiTheMonk** [nos/client#121]
When I choose nOSLocal environment from the nOs client settings, it does not use my Neo local private environment but instead an unknown environment. 

## Expected Behavior

when I choose nOSLocal in the client settings combobox, it should connect to a started Neo local environment from my computer.

## Current Behavior

when I choose nOSLocal in the client settings combobox, it seems that the client is connected to an unknown server
![error](https://user-images.githubusercontent.com/38896609/39499407-f93bb29c-4dad-11e8-8805-e872e460ce00.png)

## Possible Solution

edit may 13th 2018: add a workaround 
1. pull the lastest version of nOSLocal
2. clean docker container ($ docker system prune -a) 

## Steps to Reproduce (for bugs)

1. launch Neo local environment from my computer
2. launch nOS client
3. connect for the first time with testnet wallet
4. chose nOSLocal in the client settings combobox
5. logout nOS client 
6. extract WIF from Neo local environment default wallet (neo> export wif AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y)
7. connect to nOs client with the extracted WIF

## Your Environment

* Version used: nOs local commit 49c96c4, nOS client commit 3795446

**Comment by anhanh** [comment]
I got the same issues and able to fix by remove all docker containers then make run nos-local again

**Comment by boreiTheMonk** [comment]
@anhanh thanks I update the master repo, cleaned my dockers and it worked.  
issue edited

**Comment by anhanh** [comment]
glad it worked out for you

**Comment by DalderupMaurice** [comment]
Thanks for the feedback both! 
Closing the issue as it's sovled :)
