### ISSUE TITLE
New account creation issue

### ISSUE THREAD

**Issue by syedasifraza** [nos/client#124]
Cannot new create accounts by using nOS GUI.

## Expected Behavior
It should accept passphrase and we can register new wallet accounts

## Current Behavior
When trying to create new account using nOS GUI, 
I cannot enter text, it seems text boxes disabled.
and cannot even click on Register button or Login.

## Possible Solution
May be some older and newer operating system related fixes and extensive testing required

## Steps to Reproduce (for bugs):
Steps mentioned in below GIF file link:
https://drive.google.com/file/d/1N0numsArmVb1Bf4h_1G1SqSkQREZSAtV/view?usp=sharing

## Context
Working with multiple wallet account from my dApp and need to interact with smart contract from newly created accounts. So, my testing is not working properly.

## Your Environment
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): 
Nodejs version: 9.11.1
npm version: 5.6.0
yarn version: 1.6.0

* Operating System and version (desktop or mobile): 14.04 (Desktop)

**Comment by deanpress** [comment]
Able to reproduce.

The issue is that `-webkit-app-region: drag;` is applied to `.LoginLayout` class.
