### ISSUE TITLE
Improve the Loading Splash Screen with animated text and UI tweaks

### ISSUE THREAD

**Issue by deanpress** [nos/client#130]
## Current Behavior
The current Loading splash screen does not indicate responsiveness and feels clunky due to the size and window controls.

## Possible Solution
1. Change the Loading splash screen size to 275px x 330px
2. Remove the Window controls
3. Display animated text (with entertaining phrases) that changes with random 2-4 second intervals to indicate responsiveness.
4. Below the animated text, display individual loading steps.

Reference of good loading splash (Discord):
![Loading GIF](https://i.gyazo.com/ab268e71fa0ba624eeba9d0459c023a8.gif)

**Comment by DalderupMaurice** [comment]
Would be cool if we actually could use the animation from the video
--> Having the logo as it's whole
--> like a heartbeat it little bumb/shatter
--> back to original state
or having the outlines and animating the colors inside it with a breathe effect
(I'll post some visual ideas tonight)

**Comment by Soudny** [comment]
@deanpress I'll give this a go and do it with svg animation - that should be the best way to do it. Would it be okay if I did a PR with the implementation without tying myself to the design?

I can contact some designers to do the animation, but this might be a better way to do it - one PR for implementation and one for design (where they will simply swap out the json file that represents the animation)

**Comment by mhuggins** [comment]
@Soudny I think that would be fine.  If you just want to update the splash window itself to match the size, positioning of the current loading spinner, and add some loading text below per Dean's specifications, then that would just leave the animation change as a follow-on PR.
