### ISSUE TITLE
Expand of the memory drive

### ISSUE THREAD

**Issue by mizicko** [nos/client#143]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0):
* Operating System and version (desktop or mobile):

**Comment by mhuggins** [comment]
Please complete the form and reopen once completed.
