### ISSUE TITLE
Client freeze after input wrong url format

### ISSUE THREAD

**Issue by anhanh** [nos/client#144]
## Expected Behavior
Client should continue to work if I enter wrong url or not

## Current Behavior
Client show error and doesn't work anymore

<img width="1244" alt="screen shot 2018-05-12 at 4 12 19 pm" src="https://user-images.githubusercontent.com/7079458/39955920-78e287fe-5601-11e8-8c6d-5dadc854331c.png">
<img width="1255" alt="screen shot 2018-05-12 at 4 12 53 pm" src="https://user-images.githubusercontent.com/7079458/39955928-8e50c222-5601-11e8-8303-4912e530d213.png">

## Steps to Reproduce (for bugs)

1. Login to Client
2. Input "http://" press enter in browser
3. Client show error: TypeError: Failed to construct 'URL': Invalid URL
4. Can't use client anymore

## Your Environment

* Version used:
* Environment name and version: node.js v8.8.1, yarn 1.6.0, npm 5.6.0
* Operating System and version: macOS Sierra 10.12.6

**Comment by mhuggins** [comment]
Thanks for submitting this!  I noticed this issue as well.  I've got a potential fix in another branch I'm working on.  I would submit it as a separate PR, but the branch I'm working on is shifting things around significantly.  Hopefully I can wrap up some of those changes soon.

**Comment by prozak915** [comment]
What's now o haventt sleep for 2 data foxiing this
