### ISSUE TITLE
Invocation fails using nos-local

### ISSUE THREAD

**Issue by anhanh** [nos/client#145]
An error occurs when transfer funds or invoke Smart Contract from dApp

## Expected Behavior
No error

## Current Behavior
<img width="565" alt="screen shot 2018-05-12 at 7 24 43 pm" src="https://user-images.githubusercontent.com/7079458/39961465-af1d4ec6-5660-11e8-8847-9d49d6ca754c.png">

## Possible Solution
Add 127.0.0.1 neo-nodes to your  /etc/hosts file

## Steps to Reproduce (for bugs)

1. Make run nos-local
2. Start nos-client and login
3. Try to transfer funds in Account tab or try to invoke your SC

## Your Environment

Environment name and version: node.js v8.8.1, yarn 1.6.0, npm 5.6.0
Operating System and version: macOS Sierra 10.12.6

**Comment by jeroenptrs** [comment]
This is fixed in the new version of `nos-local`.
If you're on OSX, use your public or [local IP](https://www.whatismybrowser.com/detect/what-is-my-local-ip-address) where I placed `ip` with this command (in the nos-local folder)
`HOST_NAME=ip SEED_LIST=ip make run`
