### ISSUE TITLE
nOS Ledger tab blocks installation of NEO on Ledger nano. 

### ISSUE THREAD

**Issue by atmahesh8** [nos/client#149]
An error message when I tried to install NEO using Ledger Nano S app, and nOS - Ledger tab is open. 

## Expected Behavior
nOS ledger tab should not read Ledger nano and block Nano Ledger apps to install apps. 

## Current Behavior
nOS ledger tab is reading Ledger nano and blocking Nano Ledger to install the NEO app. 

## Possible Solution
Display the message that USB is detected but no NEO app is detected. 

## Steps to Reproduce (for bugs)
1. Go to Ledger tab in nOS
2.  wait to connect to ledger nano S hardware. 
<img width="411" alt="screen shot 2018-05-14 at 9 46 43 pm" src="https://user-images.githubusercontent.com/39273533/40011979-f67f1170-57c6-11e8-9e34-db057a25e0ee.png">
3. Open ledger Manager in Chrome to install NEO Error message 
<img width="635" alt="screen shot 2018-05-14 at 9 50 31 pm" src="https://user-images.githubusercontent.com/39273533/40011946-e3b16b4c-57c6-11e8-9cd5-ed5eae4396f9.png">

## Context
I haven't seen any negative side effects of this issue - although message is a bit misleading

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): Yarn 1.5.1 / 1.6.0, Node v8.9.1 / v10.1.0
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by tjuretzek** [comment]
After some testing, it looks like this can't be fixed. If a program is open, that asks for the Ledger, the Ledger Manager blocks any installations/changes on the ledger (for security reasons?). I tested this with several crypto wallets.

In the Ledgers trouble shooting guide for this error (https://support.ledgerwallet.com/hc/en-us/articles/115005171425-Unable-to-install-application) it states:

> **The "Unable to install applcation" error message on your Ledger Manager is displayed for several issues:** 
>not enough space on the chip OR something avoiding the Ledger Manager to recognize how much space is left on the device.

I think checking for the right app to be open on the Ledger does keep the Ledger busy so it can't _recognize how much space is left on the device_

**Comment by mhuggins** [comment]
Given the above, I'm going to close this issue.
