### ISSUE TITLE
NEO app in nano ledger is not required to open to login to nOS

### ISSUE THREAD

**Issue by atmahesh8** [nos/client#150]
NEO app in nano ledger is not required to open to login to nOS, when it is already accessed once. 

## Expected Behavior

nOS ledger tab login button should be disabled and not allowed to login without NEO app in ledger open. 

## Current Behavior

nOS ledger tab login button is enabled and allowing to login without NEO app in ledger open. 
https://drive.google.com/file/d/148Py97VniIeIcczrufzX3yEFHacJ5wMk/view?usp=sharing

## Possible Solution

Disable login button when it is detected that NEO app is not open. 

## Steps to Reproduce (for bugs)

1. Go to Ledger tab in nOS
2.  Connect Ledger Nano S to USB
3.  Open NEO app in Ledger Nano S
4. Click login button in Ledger tab in nOS
5. click logout after login to nOS client
6. close NEO app in Ledger nano S or disconnect Ledger nano S from USB
7. Click login button in Ledger tab in nOS - able to login with previous session(public key is displayed on account tab)

## Context

User should not be allowed to login to multiple apps using NANO ledger S. it's a must-fix.

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): Yarn 1.5.1 / 1.6.0, Node v8.9.1 / v10.1.0
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by jeroenptrs** [comment]
@atmahesh8 That's weird, but you do have a NEO private key stored on your ledger?

**Comment by atmahesh8** [comment]
Yes, NEO private key are stored in ledger. I could login ETH wallet ledger and nOS client at the same time.

**Comment by atmahesh8** [comment]
In fact, I disconnected by Ledger nano and could login to nOS by just click of login button. I think it is not being logged out properly and retaining the session.

**Comment by atmahesh8** [comment]
@jeroenptrs , can you give some pointers to troubleshoot by looking at logout functionality. I have asked for help on discord as well.

**Comment by atmahesh8** [comment]
found the js files. looking at it. thx

**Comment by atmahesh8** [comment]
Though no Ledger connected ,able to see connected to Ledger. 
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/39273533/40223804-d9a2183a-5aa1-11e8-8bd6-7d286804ffc3.png">

**Comment by mhuggins** [comment]
This has been fixed.
