### ISSUE TITLE
error message on ledger tab of nOS

### ISSUE THREAD

**Issue by atmahesh8** [nos/client#151]
Error on Ledger tab when connected to NEO ledger S

## Expected Behavior
It should ask to open NEO app

## Current Behavior
Throws an error

<img width="405" alt="screen shot 2018-05-14 at 11 11 39 pm" src="https://user-images.githubusercontent.com/39273533/40014105-3b0c54f0-57cd-11e8-806c-004b91f71fb4.png">

## Possible Solution
*edited by @jeroenptrs*

* Determine why this error is shown
* If it's something that can be fixed within nOS, fix it
* If not, show a more detailed reason **why** this error is shown

## Steps to Reproduce (for bugs)
1. login using NEO app of Nano ledger OS
2. logout
3. login using wallet file 
4. logout
5. go to ledger tab 
6. Error message shown as given above. 

## Context
* User should not get this error.

## Your Environment
* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): Yarn 1.5.1 / 1.6.0, Node v8.9.1 / v10.1.0
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by jeroenptrs** [comment]
@atmahesh8 why should this error *not* be shown? Why is this error not correct?

**Comment by atmahesh8** [comment]
I'm sorry, I couldn't reproduce this error.  feel free to close it or if if I will find it again during testing- will troubleshoot it and report it.
