### ISSUE TITLE
Clicking the browser icon resets the browser view to nos://nos.neo

### ISSUE THREAD

**Issue by jeroenptrs** [nos/client#155]
## Expected Behavior
If I'm already using the browser, and move to another view (f.e. profile), it should go back to the view/tab that I'm using.

## Current Behavior
Clicking the browser icon resets the browser, navigating to `nos://nos.neo/`

## Possible Solution
* Initializing the browser view
* If the component gets unmounted on navigation to a different view, don't unmount.
* Return to that view on navigation from a different view, instead of unmounting

## Steps to Reproduce (for bugs)
1. If a dapp is open, or something on localhost, in the browser, navigate to profile
2. Back to browser

## Context
Resetting the browser is a nice option, but the browser icon should act more as a `return to existing browser, OR create a new one if there's no existing one`.

## Your Environment
* Version used: current dev build
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): yarn 1.5.1, node 8.11.0
* Operating System and version (desktop or mobile): macOS sierra

**Comment by jeroenptrs** [comment]
@mhuggins I know you're working on tabs/browser stuff, if this issue is already resolved in your branch feel free to close this!

**Comment by mhuggins** [comment]
I restated this since there's more to consider with tabs.  Going to track this under #161.
