### ISSUE TITLE
Black application window when open example-neoblog

### ISSUE THREAD

**Issue by zotona** [nos/client#167]
at actual develop branch 
when i started example-neoblog and nos-client

in nos-clinet in address field i type nos://localhost:1234 and saw only black screen.

but before 8 may, it was ok and neoblog working properly.

is seems regression after this commit
```
commit 31cc08cc8d6437e74a8c23c06c3dbe2afd31e264
Author: Matt Huggins <matt.huggins@gmail.com>
Date:   Tue May 8 09:44:39 2018 -0500
```

* Version used: 
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): npm 5.6.0, yarn v1.5.1 
* Operating System and version (desktop or mobile): macOS

**Comment by jeroenptrs** [comment]
@zotona you need to add `--no-hrm` to the `start` script in the starter kit.

I'm also closing this issue because you're not using the Issue template.

**Comment by mhuggins** [comment]
@jeroenptrs `nos://localhost:1234` is preferred, so long as HRM is disabled.  I think this falls in line with the idea that we not inject the nOS API unless we're on the `nos` protocol.
