### ISSUE TITLE
CoZNet not properly working

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#169]
## Expected Behavior
account tab shows balance

## Current Behavior
fails to load - console outputs `http://localhost:3000/undefined/v2/network/nodes `

## Possible Solution
Update neon-js (3.7.0 or higher) as this PR https://github.com/CityOfZion/neon-js/pull/225 fixes the error and is included in version 3.7.0

## Steps to Reproduce (for bugs)
1. Go to settings
2. Change to CoZNet
3. Go to account tab

## Your Environment
any version gives this error

**Comment by DalderupMaurice** [comment]
Fixed with #172 & enabling of greenkeeper

**Comment by jarindr** [comment]
I was pushing this small PR and the issue was gone @DalderupMaurice lol

**Comment by DalderupMaurice** [comment]
These won't occur now with greenkeeper enabled 😄 @jarindr
