### ISSUE TITLE
Only inject nos API when browsing over the nos protocol

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#171]
## Expected Behavior
The client should only inject the API when browsing on the `nos` protocol

## Current Behavior
It's always injected

## Possible Solution
The `preloadRenderer.js` script should detect the protocol based upon `window.location`, and conditionally inject the nOS API into the `window`.

## Steps to Reproduce (for bugs)
🤔

## Context
The client should only inject the API when browsing on the `nos` protocol.

**Comment by deanpress** [comment]
Shouldn't this be injected in both cases? I can imagine HTTP apps also benefiting from the nOS protocol.

**Comment by DalderupMaurice** [comment]
@mhuggins
