### ISSUE TITLE
Browsing to a non-existing webpage should display a 5xx error page

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#188]
## Expected Behavior
Browsing to a non-existing address should display a 5xx error page.

## Current Behavior
It shows a blank page (loads nothing)

## Possible Solution
Update the DAppContainer component to listen for webview [did-fail-load](https://electronjs.org/docs/api/webview-tag#event-did-fail-load) events.  In such a case, render a custom component that gives details about the `errorCode` and `errorDescription`.

reference: https://github.com/nos/client/issues/188#issuecomment-395820523

## Screenshot
![](https://i.imgur.com/u5TznHs.png)
![](https://i.imgur.com/alkxGg6.png)

## Steps to Reproduce (for bugs)
1. Surf to any website/dapp (either on the nOS OR http(s) protocol) that does not exist
2. Look

## Context
It's not clear that it doesn't exist

## Your Environment
any

**Comment by kitchenSpoon** [comment]
Can we add a game here? =)

**Comment by DalderupMaurice** [comment]
That would be fun 😂 
Not sure about the impact of performance though 🤔 @kitchenSpoon @mhuggins

**Comment by mhuggins** [comment]
Seems like a fun feature, but I wouldn't consider it a part of the core feature work for this story.  I think we should focus on MVP features, then we could add a community issue if we want to allow for that to be added.

**Comment by DalderupMaurice** [comment]
Added the future tag @mhuggins

**Comment by mhuggins** [comment]
Sorry.  To clarify, I meant the game in the 404 page.  I don't think a 404 page should be "future".

**Comment by robmoorman** [comment]
This seems to be a nice placeholder for it:
```javasript
  handleNavigateFailed = (_event) => {
    // TODO: Display an error page or something.  For now, just clear out the loading spinner.
    this.props.setTabLoaded(this.props.sessionId, true);
  }
```

**Comment by mhuggins** [comment]
I believe we should be able to use `about` pages in the style of Chrome, but I haven't invested time into figuring out if we truly can and how to do that with electron yet.  I think that might be one possibility here.

**Comment by robmoorman** [comment]
Drawn some steps to take before making the PR:

## 1) Adding a redux action 

Looking to the future we might also provide 500 error pages, instead of setting "errors to true/false" it should be better to display other content based on http status code.

```javascript
export const setTabTargetHttpStatus = (sessionId, statusCode) => ({
  type: SET_TAB_TARGET_HTTP_STATUS,
  sessionId,
  statusCode // The HTTP status code, e.g. 404 for page not found
});
```

## 2) Add a static 404 page in the code base (lives near the index.html)

public/404.html
public/500.html

## 3) Determine target url based of state

This can be pragmatically done in the `render` method of `DAppContainer`.
Another way is to accomplish this with e.g. `withPropsOnChange` via `recompose` (to get as much business logic out of the component as possible).

**Comment by mashi-als** [comment]
Isn't it different cases, requestion unexisting host (cannot be resolved) and requesting a non-existent resource from a host. I believe in the first case nos client should show placeholder (nos domain cannot be resolved) but in the second case, it is the responsibility of a dApp to handle requests to non-existent pages.

**Comment by nasuru1** [comment]
Creating a custom 404 page for your GitHub Pages site
You can display a custom 404 error page when people try to access nonexistent pages on your site.

Navigate to your GitHub Pages repository.
Switch to the master branch for a User/Organization Pages site, or to the gh-pages branch for a Project Pages site.
Create a HTML file named 404.html or create a new Markdown file named 404.md at the root level of your GitHub Pages repository.
In the YAML front matter of your new 404 file, add permalink: /404.html.
Add the content you want to display to lost souls and weary travelers.
Commit your changes and, if you're working on a local clone of your repository, push them up to GitHub.

**Comment by mhuggins** [comment]
I dug into the electron side of this a bit.  We should be able to use the [did-fail-load](https://electronjs.org/docs/api/webview-tag#event-did-fail-load) webview event to determine if content failed to load for any reason.  In such a case, we can render a custom React component based upon the `errorCode` and `errorDescription`.

**Comment by mhuggins** [comment]
There are negative values as well, as seen in that link.  We should account for any of them.

**Comment by robmoorman** [comment]
Jeah. Working on a PR right now @mhuggins we can shoot on it later this night, keep you posted.
