### ISSUE TITLE
Welcome screen loads as text/plain in distributable/executable

### ISSUE THREAD

**Issue by mhuggins** [nos/client#208]
## Expected Behavior
When using `yarn dist` to create an executable, the welcome screen (i.e.: `nos://nos.neo`) should display with proper HTML styling, just as it does when running `yarn start`.

## Current Behavior
The welcome screen is loaded as text/plain instead of text/html, rendering all file content directly in the webview.

## Possible Solution
This relates to the way `registerHttpProtocol` is being used.  There is no content-type header since we're loading via the `file://` protocol, so we will need to either find a way to add a content-type header, or change the way we load the file.

## Steps to Reproduce (for bugs)
1. Run `yarn dist`
2. Run the executable file that was generated for your OS
3. Login to any NEO account
4. Observe the browser/webview output on the welcome screen (`nos://nos.neo`).

## Context
We would like to release a 0.2.0 build, but this is a blocker.

## Your Environment
* Version used: `develop` branch at a47f41a0fe6c33d0f18813ff5d77fc38a5467570
* Environment name and version: node 8.9.3, yarn 1.5.1, npm 5.5.1
* Operating System and version: macOS High Sierra 10.13.3

**Comment by deanpress** [comment]
Possible solution would be having the client boot up a local express server and then serving the files through there.

**Comment by mhuggins** [comment]
An alternate that I was playing with is replacing `registerHttpProtocol` with `registerStreamProtocol`.  This would allow us to use `fs.createReadStream` for files and the [request package](https://www.npmjs.com/package/request) for http(s).  The benefit of the stream protocol is that we can supply headers (and thus content-type for files).

**Comment by mhuggins** [comment]
I have a WIP branch from this morning for my above idea: https://github.com/nos/client/compare/chore/fix-nos-local-files
