### ISSUE TITLE
Support cut/copy/paste on standard inputs

### ISSUE THREAD

**Issue by dennisschaaf** [nos/client#218]
On the login form it's not possible to paste in private keys (WIF), because the right-click menu and keyboard shortcuts are disabled.

## Expected Behavior
* Press <kbd>Ctrl</kbd>+<kbd>V</kbd> (Windows/Linux) or <kbd>Cmd</kbd>+<kbd>V</kbd> (macOS) within the input field.
* Right-click on the input field, and select "Paste" from the context menu that appears.

## Current Behavior
Nothing happens.

## Possible Solution
Specify menu items in the main process, as explained [here](https://github.com/electron/electron/issues/2591#issuecomment-134782703).

## Steps to Reproduce (for bugs)
1. Open nOS.
2. Try to sign-in by copy and pasting your WIF.

## Context
Any input field.

## Your Environment
* nOS Version: 0.2.0
* Operating System: macOS

**Comment by mhuggins** [comment]
Thanks for adding this issue, we've had several reports of this.  Copy/paste works in development mode, but not in the distributable.  This electron issue explains why: https://github.com/electron/electron/issues/2591#issuecomment-134782703

**Comment by mhuggins** [comment]
I've updated your issue description to include more context for anyone who picks this up.

**Comment by mhuggins** [comment]
[electron-context-menu](https://github.com/sindresorhus/electron-context-menu) might be worth looking into as well.

**Comment by mhuggins** [comment]
Assigning this to myself, I've almost got this wrapped up.
