### ISSUE TITLE
Implement electron-redux

### ISSUE THREAD

**Issue by mhuggins** [nos/client#220]
## Expected Behavior
Both the main & renderer processes should be able to interact with the redux store.

## Current Behavior
The renderer owns and interacts with the store, and data is not shared between processes.

## Possible Solution
Implement [electron-redux](https://github.com/hardchor/electron-redux).  This is blocked by #166.

## Steps to Reproduce (for bugs)
N/A

## Context
In order to provide app controls (such as menus), the main process needs to have access to the redux store.

## Your Environment
* Version used: 0.2.0
* Environment name and version: Any
* Operating System and version: Desktop

**Comment by DalderupMaurice** [comment]
As an addition - we should move over to webpack aswell 4?

**Comment by mhuggins** [comment]
I'd like to keep that separate.  I already tried to upgrade, but ran into many complications.  Webpack 4 is honestly not ready for real world use from what I've seen.

**Comment by mhuggins** [comment]
Taking this off the 0.3.0 roadmap for now since it's no longer a blocker for some of the design work I'm doing.
