### ISSUE TITLE
Add back, forward and reload buttons to browser

### ISSUE THREAD

**Issue by robmoorman** [nos/client#231]
## Current Behavior
None of these controls are available. It makes it impossible to navigate through history.

## Possible Solution
Extend the browser bar and add new components. Actions should control the webview component:
https://electronjs.org/docs/api/webview-tag#methods (e.g. `<webview>.canGoBack()`, etc.)

**Comment by skylineblvd7** [comment]
Just submitted a pull request for a partial enhancement (just the reload button).
