### ISSUE TITLE
nOS icon/logo not showing in appbar on Linux

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#261]
## Expected Behavior
nOS icon displays on the Linux appbar for both the development and distributable versions.

## Current Behavior
nOS only displays on the Linux appbar for only the development version, not the distributable version.

## Possible Solution
Update build to account for icon on linux.

## Steps to Reproduce (for bugs)
1. Run `yarn dist` (or download v0.2.1) on a linux machine.
2. See icon bar when launching dist version of nOS.

## Context
The experience of launching the application should be uniform across platforms.

## Your Environment
* Version used: 2.1.0
* Environment name and version: All
* Operating System and version: Linux

**Comment by skylineblvd7** [comment]
hmm unless I am misunderstanding this bug, the icon is indeed showing. here is a snapshot.
![screen shot 2018-06-26 at 7 17 41 am](https://user-images.githubusercontent.com/39974682/41918476-46e9d4e0-7911-11e8-9006-25bf75119b4f.png)

**Comment by DalderupMaurice** [comment]
We mean the logo in the appbar/launchbar @skylineblvd7

**Comment by skylineblvd7** [comment]
sorry - you mean ever before you login? like this?
![screen shot 2018-06-26 at 10 09 53 am](https://user-images.githubusercontent.com/39974682/41928173-2c1e9c8c-7929-11e8-9994-adc78831beb7.png)

not quite understanding where the appbar/launchbar is other than what I see.

**Comment by DalderupMaurice** [comment]
This is the appbar. I am on windows, but Linux has it by default on the left side
![](https://i.imgur.com/5c9G7Bu.png)

**Comment by jeroenptrs** [comment]
🙈 maybe post a screenshot of the image not loading in all os'es app bars? @DalderupMaurice

**Comment by skylineblvd7** [comment]
@jeroenptrs @DalderupMaurice  - thanks for your feedback and patience. I have tried this with two different window managers but I can not reproduce the issue. Please see the snapshots below.

![screen shot 2018-06-26 at 8 58 06 pm](https://user-images.githubusercontent.com/39974682/41952699-34e56f1e-7986-11e8-849e-1fc20cda7d04.png)
![screen shot 2018-06-26 at 9 07 26 pm](https://user-images.githubusercontent.com/39974682/41952708-3f6a3a28-7986-11e8-8d75-a9399b3fa87c.png)

**Comment by DalderupMaurice** [comment]
Hmm alright, thanks! @deanpress did have the issue on his Laptop - could you verify this? @deanpress

**Comment by deanpress** [comment]
@DalderupMaurice The icon works with `yarn start`, not with the compiled build. See below (left is dev build, right is compiled 0.2.1 release):
![https://i.gyazo.com/2100cbaa1cba1281a1cbb1dc88c0a851.png](https://i.gyazo.com/2100cbaa1cba1281a1cbb1dc88c0a851.png)

**Comment by DalderupMaurice** [comment]
Updated the description. cc @skylineblvd7

**Comment by mhuggins** [comment]
@DalderupMaurice Is this still an issue?

**Comment by DalderupMaurice** [comment]
cc @deanpress 
I think this is still an issue with the current build?

**Comment by deanpress** [comment]
@DalderupMaurice @mhuggins Yes, the icon is still missing in dist.
