### ISSUE TITLE
Create Account and Saved Accounts (Encrypted)

### ISSUE THREAD

**Issue by deanpress** [nos/client#27]
On the authentication window, the Passphrase tab should provide the option for users to create new accounts, and to save them on creation or log-in.

Similar to `neon-wallet`, users should be able to select previously saved accounts (only encrypted keys) so they only have to enter their Passphrase to log in.

**Comment by mhuggins** [comment]
This is done!

**Comment by mhuggins** [comment]
My mistake -- we're saving the wallet file, but we're not providing login with a prepopulated dropdown of accounts anywhere.  I believe that's what the intention of this issue is, is that right @deanpress?

**Comment by kitchenSpoon** [comment]
@deanpress , @mhuggins we do have the functionality on the Wallet file Tab though

<img width="1362" alt="screen shot 2018-05-05 at 1 49 27 am" src="https://user-images.githubusercontent.com/2775497/39637495-92738fb6-5006-11e8-9bd5-8e526b459d1b.png">
![Uploading Screen Shot 2018-05-05 at 1.49.23 am.png…]()

**Comment by mhuggins** [comment]
This is unencrypted though.  It's not ideal to have a plaintext wallet file sitting on your computer.  We may still want to support storing encrypted keys that depend on passphrase, which can then prepopulate in a `select` within the "passphrase" tab.

**Comment by kitchenSpoon** [comment]
Ahh, I see thanks

**Comment by DalderupMaurice** [comment]
What's the status of this issue? @mhuggins 
KitchenSpoon's PR is merged already :P

**Comment by mhuggins** [comment]
Closing!
