### ISSUE TITLE
Move to docusaurus

### ISSUE THREAD

**Issue by jeroenptrs** [nos/client#272]
## Describe the solution you'd like and the expected behavior
Move `docs` to a documentation repo, so we can host documentation centralized on the nOS website.

## Is your feature request related to a problem? Please describe.
/

## Possible implementation / References
Use docusaurus in new repo, add `docs.nos.io` to github pages, ???, profit.

## Additional context
/

**Comment by DalderupMaurice** [comment]
Sorry! I've completely overlooked this issue :( @skylineblvd7 
We've moved the docs now to the document branch

If you see any missing pieces, feel free to update them!
