### ISSUE TITLE
Remove webview tag warnings from `yarn test`

### ISSUE THREAD

**Issue by mhuggins** [nos/client#277]
## Expected Behavior
Running `yarn test` does not output any warnings about invalid DOM elements.

## Current Behavior
Running `yarn test` outputs warnings about invalid DOM elements.

>     console.error node_modules/fbjs/lib/warning.js:33
>       Warning: The tag <webview> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

## Steps to Reproduce
1. `yarn test`

## Possible Solution
According to [this comment](https://github.com/facebook/jest/issues/3698#issuecomment-340767259), this can be fixed by running jest via:

```
ELECTRON_RUN_AS_NODE=true ./node_modules/.bin/electron ./node_modules/.bin/jest
```

I tried this though, and it doesn't seem to work.

## Additional context
This started happening after switching from react-scripts (i.e.: create-react-app) to electron-webpack and jest.

## Your Environment
* nOS Client version used: 0.2.0
* Environment name and version
    * Node version: 8.11.3
    * NPM version: 5.6.0
    * Yarn version: 1.5.1
* Operating System and version (desktop or mobile): macOS High Sierra 10.13.3

**Comment by DalderupMaurice** [comment]
CLOSED!!! By updating react
