### ISSUE TITLE
Could not find 'check-circle' icon

### ISSUE THREAD

**Issue by dkoziy** [nos/client#281]
## Expected Behavior
After changing selected network on settings page you should see message 'Saved!' and 'check-circle' icon near dropdown

## Current Behavior
Now I see only message 'Saved!' and errors in console about missing icon

![screenshot with errors](http://dl4.joxi.net/drive/2018/06/26/0025/3262/1690814/14/ad3d018ed7.jpg)

## Steps to Reproduce
1. Open settings page
2. Change selected network 

## Possible Solution
It happens because of missing 'far' prefix for this icon in `Icon` component. And fixing it will require little styles for `Saved` component. I want to implement this fix, and maybe we don't need this text 'Saved!' at all, if icon will be visible? What are you thinking about it?

## Your Environment
I think that environment doesn't matter in this case

**Comment by mhuggins** [comment]
Thanks for reporting! Looks like this broke with a recent font awesome upgrade.
