### ISSUE TITLE
Use RPC `getaccountstate` for asset balances

### ISSUE THREAD

**Issue by mhuggins** [nos/client#282]
## Describe the solution you'd like and the expected behavior
When fetching asset balances (for NEO & GAS), use RPC [getaccountstate](http://docs.neo.org/en-us/node/cli/2.7.6/api/getaccountstate.html) rather than neoscan.

## Is your feature request related to a problem? Please describe.
We're currently using neoscan to fetch asset balances.  However, this introduces a single point of failure, and neoscan has been found to fall behind and been inaccurate at times.

## Possible implementation / References
Within the `getBalances` function, use neon-js to get the address for an RPC endpoint, then construct the request against it.

**Comment by DalderupMaurice** [comment]
This can be closed right, it's implemented in `getBalances` right now (I remeber seeing this a couple PR's before) @mhuggins

**Comment by DalderupMaurice** [comment]
closing this https://github.com/nos/client/pull/398
