### ISSUE TITLE
Minimize/Maximize/Close button not clickable

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#310]
## Expected Behavior
Buttons should be clickable
This is caused by switching the tabs and url bar

## Current Behavior
The AuthenticatedLayout is on top of it, rendering the buttons useless

## Steps to Reproduce
1. open client
2. click close, min or maximize button
3. nothing happens

## Possible Solution
move the buttons above the authenticatedLayer

## Your Environment
* nOS Client version used: 0.2.1
* Environment name and version
    * Node version: any
    * NPM version: any
    * Yarn version: any
* Operating System and version (desktop or mobile):

**Comment by dkoziy** [comment]
It's caused because of `-webkit-app-region: drag`. I would like to fix it and maybe create some tests for future

**Comment by dkoziy** [comment]
I've created PR with quick fix, and I'll try to make some tests later, when I'll have time for it
