### ISSUE TITLE
Prevent normal web browsing

### ISSUE THREAD

**Issue by mhuggins** [nos/client#33]
We don't want normal links to work.  We should highjack navigation with electron to prevent it.

Note that webview does not support `event.preventDefault()` on the [will-navigate IPC event](https://electronjs.org/docs/api/webview-tag#event-will-navigate).  Instead, we'll need to use `preloadRenderer.js` to prevent navigation.  An example of how to do this can be found here: https://github.com/electron/electron/issues/4191#issuecomment-245872167.

**Comment by DalderupMaurice** [comment]
Is this still an issue? 
As we're planning on only injecting the nOS API on urls with the nos protocol? @mhuggins

**Comment by mhuggins** [comment]
I think we should close this and open another issue to inject the nOS API only for sites loaded under the `nos` protocol.
