### ISSUE TITLE
Clicking a menu item opens it in a new tab every time

### ISSUE THREAD

**Issue by deanpress** [nos/client#339]
## Expected Behavior
If a menu item tab is already opened in a tab (active or inactive), clicking the menu item should cause the browser to switch to that item's tab.

## Current Behavior
Every time you click on e.g. "Account", a new tab opens with the Account page.

## Steps to Reproduce
1. Pull the latest develop release
2. Start the client and log in
3. Click on any menu item repeatedly
4. Watch a new tab open with every click

## Your Environment
* nOS Client version used: develop/latest
* Operating System and version (desktop or mobile): Linux Mint 18

**Comment by jeroenptrs** [comment]
👍 this is how i ended up unwillingly with 20 open account and settings tabs 😅
