### ISSUE TITLE
Support additional browser shortcuts (Mouse 3/4/5 & Ctrl+R behaviors)

### ISSUE THREAD

**Issue by deanpress** [nos/client#341]
## Describe the solution you'd like and the expected behavior
The following shortcuts should be usable:
1. Cmd/Ctrl + R for refreshing a tab
2. Middle Mouse (Mouse3) for opening anchors in new tabs
3. Pressing Middle Mouse on a Tab to close it
4. Mouse4/Mouse5 for history navigation (Backward/Forward)

## Possible implementation / References
#193 implemented several shortcuts.

**Comment by mhuggins** [comment]
We'll want these to be tied to menu options.  The menu options config can be found [here](https://github.com/nos/client/blob/develop/src/main/util/bindContextMenu.js).

**Comment by mhuggins** [comment]
This change should include the back/forward/reload behavior for the address bar icons as well.

**Comment by jeroenptrs** [comment]
@mhuggins @deanpress this issue should include the macOS swipe gestures for goBack/goForward too

**Comment by mhuggins** [comment]
I have a WIP branch for this stuff.  I'd like to at least include the menu items + shortcut keys in 0.3.0.  Anything I can't wrap up before then (probably mouse gestures), I'll move into a separate issue.
