### ISSUE TITLE
Webcam not working with nos://

### ISSUE THREAD

**Issue by syedasifraza** [nos/client#345]
## Expected Behavior
It should detect webcam with nos protocol. 

## Current Behavior
It is showing black webveiw when I am trying to scan qr codes by using webcam.
I used following react qr reader component: https://www.npmjs.com/package/react-qr-reader 

## Steps to Reproduce
write this code:
```
'use strict'
const React = require('react')
const ipfsAPI = require('ipfs-api')

class App extends React.Component {
  constructor () {
    super()
    this.state = {
      added_file_hash: null
    }
    this.ipfsApi = ipfsAPI('150.183.234.117', '5001')

    // bind methods
    this.captureFile = this.captureFile.bind(this)
    this.saveToIpfs = this.saveToIpfs.bind(this)
    this.handleSubmit = this.handleSubmit.bind(this)
  }

  captureFile (event) {
    event.stopPropagation()
    event.preventDefault()
    const file = event.target.files[0]
    let reader = new window.FileReader()
    reader.onloadend = () => this.saveToIpfs(reader)
    reader.readAsArrayBuffer(file)
  }

  saveToIpfs (reader) {
    let ipfsId
    const buffer = Buffer.from(reader.result)
    this.ipfsApi.add(buffer, { progress: (prog) => console.log(`received: ${prog}`) })
      .then((response) => {
        console.log(response)
        ipfsId = response[0].hash
        console.log(ipfsId)
        this.setState({added_file_hash: ipfsId})
      }).catch((err) => {
        console.error(err)
      })
  }

  handleSubmit (event) {
    event.preventDefault()
  }

  render () {
    return (
      <div>
        <img src="https://ipfs.io/ipfs/QmWnwddX5JY9pWkmpCY9hWVaiwYp8qyQ9RzAFKzBdDvii2" width="500" height="333" />
        <img src="https://ipfs.io/ipfs/QmQ1YZbdzUQEAmBBJip6vAqrD5Nt8rmirqASbSKE3bqFcf" width="500" height="333" />
        <form id='captureMedia' onSubmit={this.handleSubmit}>
          <input type='file' onChange={this.captureFile} />
        </form>
        <div>
          <a target='_blank'
            href={'https://ipfs.io/ipfs/' + this.state.added_file_hash}>
            {this.state.added_file_hash}
          </a>
        </div>
      </div>
    )
  }
}
module.exports = App
```

execute code with nos protocol and start reading qr code and it will show you blank webview
However, same code is working with http://localhost

## Possible Solution
May be nos protocol require to support native APIs.
As per description in: https://www.npmjs.com/package/react-qr-reader 
qr reader work with localhost and https only, this may help you to understands further.

## Additional context
I cannot read qr code for my dApp

## Your Environment
* nOS Client version used:
* Environment name and version
    * Node version: 9.11.0
    * NPM version: 6.1.0
    * Yarn version: 1.6.0
* Operating System and version (desktop or mobile): desktop ubuntu 14.0

**Comment by lrypto** [comment]
should be the same or related to the issue i put up #375 (get user media is not exposed yet).

**Comment by mhuggins** [comment]
Going to track this under #375 since that has more research comments in it.
