### ISSUE TITLE
GetBalance for token returns 0

### ISSUE THREAD

**Issue by benjyz** [nos/client#350]
## Expected Behavior
nos.getBalance({ asset: "ed07cffad18f1308db51920d99a2af60ac66a7b3" }) returns the balance of the wallet (1.0)

## Current Behavior
the function call returns 0

## Steps to Reproduce
1. nos.getBalance({ asset: "ed07cffad18f1308db51920d99a2af60ac66a7b3" }) 

## Your Environment
* nOS Client version used: recent
* Environment name and version
    * Node version: 8.11
    * NPM version: 5.6.0
    * Yarn version: 0.23.2

* Operating System and version (desktop or mobile):
OSX

**Comment by mhuggins** [comment]
Looks like Phantasma's [SOUL](https://neotracker.io/asset/ed07cffad18f1308db51920d99a2af60ac66a7b3) token on MainNet for reference.

@benjyz Was this happening on MainNet?

**Comment by benjyz** [comment]
@mhuggins yes, MainNet. should test other NEP5?

**Comment by mhuggins** [comment]
I don't personally have any SOUL to test against, but I'll test against some other tokens.

**Comment by DalderupMaurice** [comment]
I tried this with another NEP-5 Token as I do not own SOUL and got the correct result.
Could you check the correct Network was selected? @benjyz

**Comment by mhuggins** [comment]
I've heard about there being issues with SOUL in neon-wallet as well, but don't know the details/background/end result.

**Comment by jeroenptrs** [comment]
Could this be the same issue as with the NNS tokens? (Not showing up in specific nodes etc)

**Comment by benjyz** [comment]
this is definitely bug. why not ask more info first?

**Comment by DalderupMaurice** [comment]
It's not an issue within the nOS Client @benjyz
