### ISSUE TITLE
clicking account button in nOS 0.2.2 leads to a failed loading page windows 10 x64 

### ISSUE THREAD

**Issue by eyeboot** [nos/client#380]
## Expected Behavior
Clicking the account button where you could see a page showing the linked neo and NEP5 addresses. A profile page where you can customize aspects of your account and control privacy features.

## Current Behavior
When clicking the account button, the account pages fails to load and we are shown a "failed to load screen: nOSNet"

see screenshot below:
![failed to load](https://user-images.githubusercontent.com/41872216/43368665-65081c4c-9393-11e8-8566-98e0ac8339c1.jpg)

## Steps to Reproduce
1. download nOS-0.2.2-Windows.exe installer from this link:
https://github.com/nos/client/releases/download/0.2.2/nOS-0.2.2-Windows.exe
2. run installer
3. create / import account
4. verify email
5. login to nOS account
6. click account button on left panel

## Additional context
unable to see neo address linked to my account, had to click browser button and refresh. then click settings before i could find requested info.

## Your Environment
* nOS Client version used: nOS-0.2.2-Windows
* Operating System and version (desktop or mobile): desktop Windows 10 x64

**Comment by mhuggins** [comment]
Thanks for reporting!  Since this is already fixed on the `develop` branch, I'm going to close it.  This fix will be included with the next release.
