### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by mhuggins** [nos/client#404]
## Describe the solution you'd like and the expected behavior
When settings are saved, a flash message should display to the user.  This would also be useful for other places, such as when the user copies his address in the "Receive" tab.

## Is your feature request related to a problem? Please describe.
It's not clear to the user that their settings have saved unless we provide feedback.

## Possible implementation / References
N/A

## Additional context
![Screen Shot 2018-08-05 at 9.21.56 AM.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/6d2606b3-c628-43fb-be93-978604c89b93)

**Comment by DalderupMaurice** [comment]
Probably going to use react portals to achieve this? @mhuggins

**Comment by mhuggins** [comment]
I think so. 😄
