### ISSUE TITLE
Favicon on browser tabs

### ISSUE THREAD

**Issue by mhuggins** [nos/client#410]
## Describe the solution you'd like and the expected behavior
When a favicon is available for a page, it should be displayed in the tab.

## Is your feature request related to a problem? Please describe.
Favicons help to quickly scan for a tab that's already open.

## Possible implementation / References
Electron's webview has a [page-favicon-updated](https://electronjs.org/docs/api/webview-tag#event-page-favicon-updated) event, which can be used to get ahold of the favicon image URLs.  This can be used in conjunction with browserActions to track the favicon, and in turn load the image in the tab.

## Additional context
![Screen Shot 2018-08-05 at 9.44.14 AM.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/3d98608f-71ae-4982-ad6f-1f3191cce8fa)

**Comment by deanpress** [comment]
@mhuggins Can we re-add this to 0.3.0?

**Comment by mhuggins** [comment]
@deanpress I'll see if I can get this working for 0.3.1.
