### ISSUE TITLE
Clicking "Create Account" after creating account returns previous account information

### ISSUE THREAD

**Issue by deanpress** [nos/client#427]
## Expected Behavior
When you click "Create Account", you should always go to a new "Create Account" screen without pre-filled data.

## Current Behavior
If you previously created an account in the same session, going back to Create Account shows the previous account data.

## Steps to Reproduce
1. Click Create Account
2. Generate a NEO account
3. Go back to login screen
4. Click Create Account again

## Your Environment
* nOS Client version used: dev latest

**Comment by mhuggins** [comment]
Thanks for the heads up.  I think I know what caused this, so I'll take a look tonight.  I'll add some tests around it too since there's been a bit of backfilling going on there.  (Coverage is up about 12% over the last month, still chugging.)
