### ISSUE TITLE
Reduce amount of API Calls for fetching tokens

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#445]
## Describe the solution you'd like and the expected behavior
Fetch balances of tokens with a single RPC call.

## Is your feature request related to a problem? Please describe.
For every token, we're making a separate RPC call.

## Possible implementation / References
--> `src/renderer/shared/util/getBalances.js`
```js
const response = await api.nep5.getTokenBalances(endpoint, [all_tokens_scriptHashes], address);
```

## Additional context
N/A

**Comment by mhuggins** [comment]
Oh nice, I didn't realize this existed.  This would be an awesome change!

**Comment by mhuggins** [comment]
I updated this to use the Feature Request template instead of the Bug Report template. 😄
