### ISSUE TITLE
Delay on tab switching

### ISSUE THREAD

**Issue by deanpress** [nos/client#447]
## Expected Behavior
Switching tabs should be near-instant.

## Current Behavior
There's a noticeable delay when you click between tabs.

## Steps to Reproduce
1. Open nOS Client
2. Switch between tabs
3. Notice delay
4. Create issue about it on Github

**Comment by mhuggins** [comment]
@deanpress I think this may only be happening on the development build (`yarn start`).  Are you experiencing this on the distributable build (`yarn dist`)?

**Comment by deanpress** [comment]
@mhuggins Both distributables appear to be having this delay.

**Comment by jeroenptrs** [comment]
@deanpress is this still present? I don't seem to have it.

**Comment by mhuggins** [comment]
Yeah, I haven't been able to reproduce this at all. 😆
