### ISSUE TITLE
Window lacks empty space for dragging when tabs have filled top space

### ISSUE THREAD

**Issue by deanpress** [nos/client#449]
## Expected Behavior
Window should always be draggable by clicking on a blank area in the tabs bar (or by the nOS logo in the sidebar)

## Current Behavior
If the tabs cover the top bar, there's no longer a place to drag the window. I have to close a tab in order to drag it.

## Steps to Reproduce
1. Open a bunch of tabs
2. Try dragging the window

## Your Environment
* nOS Client version used: latest dev
* Operating System and version (desktop or mobile): Linux Mint 19

**Comment by DalderupMaurice** [comment]
That's because devTools are opened by default @mhuggins https://github.com/electron/electron/issues/5732
I've got a branch which adds the ability to drag using the nOS icon. I'll get it up soon if that's okay/enough to close this issue

**Comment by mhuggins** [comment]
Ahh, nice find @DalderupMaurice.  I was puzzled by the fact that I was able to drag the window again just the other day, but I did accidentally close the inspector at one point.  Probably coincides.
