### ISSUE TITLE
Update minimize/maximize/close icons for Windows/Linux

### ISSUE THREAD

**Issue by mhuggins** [nos/client#473]
## Describe the solution you'd like and the expected behavior
The window minimize/maximize/close icons should match the designs.  They should also match hover/active state that Windows has.

## Is your feature request related to a problem? Please describe.
We have new designs that do away with the stale FontAwesome icons.

## Possible implementation / References
See Figma.

## Additional context
![close-hover.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/86e6a372-081d-4812-95c3-32e353ace3f2)

![maximize-hover.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/8a83ec7c-50f3-4ed4-9a46-04839642667a)

![windows-icons.gif](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/116992ea-63fe-4d60-93c3-ea6c7564fa54)

**Comment by DalderupMaurice** [comment]
We don't have designs for this, right?

**Comment by mhuggins** [comment]
@DalderupMaurice No, but we should be able to just mimic Windows.

**Comment by DalderupMaurice** [comment]
The same icons with animations? Thought dean said the were too fat/didn't fit the client

**Comment by fabric-8** [comment]
Added the assets for this to the icons @ stylesheet:
https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=201%3A39

The styleguide now also shows a win top bar version:
https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=194%3A31311
