### ISSUE TITLE
Invocation Modal

### ISSUE THREAD

**Issue by mhuggins** [nos/client#474]
## Describe the solution you'd like and the expected behavior
The invocation modal should match the designs.  There should also be a success modal that displays once the invocation is processed & accepted by the blockchain.

## Is your feature request related to a problem? Please describe.
Implementing new designs.  This is necessary to ensure the user has enough insight regarding what they are sending.

## Possible implementation / References
Depends on #88 & #118.

## Additional context
![Screen Shot 2018-08-26 at 3.29.31 PM.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/66d36b02-3c72-4ecb-ba06-9d0fc5400224)

![Screen Shot 2018-08-26 at 3.29.44 PM.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/866b83af-45c8-4944-b2b2-37d04d0815a5)

**Comment by DalderupMaurice** [comment]
I suggest including this one aswell 
https://github.com/nos/client/issues/369
