### ISSUE TITLE
Several issues with current toasts

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#489]
// NOTE - removed expected/current behavior as I have multiple issues/suggestions.

- [ ] You cannot press log out button when a toast is active as the notification spreads across the whole width of the screen, over the button
- [ ] You cannot close notifications on the login screen. With this, you can't even click any modal in the login screen (import faulty wallet file still shows a modal, which you cannot close because of this issue)

## Steps to Reproduce
1. Uhh, try out as described :P 

## Possible Solution
???

## Additional context
//

## Your Environment
* nOS Client version used: Any version including toasts, I've been experiencing some of these issues a long time so they've been there a while already
* Environment name and version
    * Node version: any
    * NPM version: any
    * Yarn version: any
* Operating System and version (desktop or mobile): any

**Comment by mhuggins** [comment]
For the first point, we can probably just add `user-select: none` to the parent div, and `user-select: auto` to each individual toast.

**Comment by DalderupMaurice** [comment]
Doesn't work - It's related to the absolute position & having top, bottom, right, left set to 0
If I turn any of these 5 properties off, they're clickable

**Comment by jeroenptrs** [comment]
@DalderupMaurice can we close this issue now?

**Comment by DalderupMaurice** [comment]
These only solved a part of the issues (they're not listed here anymore)
The ones shown here are still unresolved

**Comment by DalderupMaurice** [comment]
closing - first issue is going to be obsolete for 0.6, 2nd is solved
