### ISSUE TITLE
Migrate from current CMC API 

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#518]
## Describe the solution you'd like and the expected behavior
Migrate current CMC to the V2. 
The currently used API is going to be dropped on December 4th, 2018 

## Is your feature request related to a problem? Please describe.
Functionality will break after December 4th, 2018

## Possible implementation / References
- Use the V2 Pro API
- Use binance API
- Any other suggestion

## Additional context
https://pro.coinmarketcap.com/
https://github.com/binance-exchange/node-binance-api
...

**Comment by robmoorman** [comment]
Quick note here @DalderupMaurice; does Electron has any kind of secrets to use?

As it's all client-side code. You'll probably expose your API key.

I've migrated some client-side apps as well over the last weeks to this new CMC V2 API. For some we have decided to read from S3 were we sync this data to (it requires a tiny worker in our infrastructure).

**Comment by jeroenptrs** [comment]
@robmoorman or you wrap it with a serverless provider. I tried wrapping the free tier of the new CMC pro API but no dice, too little requests possible.

**Comment by robmoorman** [comment]
Yup as serverless providers share outgoing ip's... Best (from performance perspective) is to serve this via a CDN. Ex. `CloudFront` -> `S3`. I could image you do the same for fiat rates. Then you also have full control over it. Just push the data from some services (for these task we have a cluster running with tiny docker containers, executing all kind of tasks periodically, works best for us).

Found an article which can be relevant though (secure these kind of api keys for electron): https://medium.com/@rocketlaunchr.cloud/introducing-electron-vault-d09ade2c2020

**Comment by DalderupMaurice** [comment]
Cool thanks! I didn't even think about the secrets yet :P
And we're also going to have a look at other API's, whether any other API would be any good.

**Comment by tmlee** [comment]
Alternatively you may consider our API at https://www.coingecko.com/api/docs/v3
no api keys needed thus simplifying the use case here
happy to answer any questions and listen to feedbacks

**Comment by tmlee** [comment]
@deanpress awesome, feel free to let me know if you have any questions!

**Comment by deanpress** [comment]
@tmlee How do you feel about a Coingecko feature to get multiple coins in one request? e.g. `/coins/nos,neo,ava,nex`?

**Comment by tmlee** [comment]
@deanpress yes you can do that using the /markets endpoint, you can in a list of `ids` 
docs at https://www.coingecko.com/api/docs/v3#/coins/get_coins_markets
we use `id` because symbols can collide

**Comment by DalderupMaurice** [comment]
done #816
