### ISSUE TITLE
Clicking the block info menu item should open a new tab to the network's block explorer (neoscan)

### ISSUE THREAD

**Issue by deanpress** [nos/client#527]
## Describe the solution you'd like and the expected behavior
Clicking the block info menu item should open a new tab to the network's block explorer

**Comment by mhuggins** [comment]
@deanpress I don't think this is going to work.  I attempted it as part of #532, but neoscan is always at least one block behind.  As a result, the user either sees an error (on nOSNet) or gets redirected to the homepage (on MainNet).

**Comment by jeroenptrs** [comment]
@mhuggins I reckon it'd be better to just link to the block explorer, not the specific block?

**Comment by jeroenptrs** [comment]
The network icon doesn't say specific block x per sé as a linking target, just a context view of the network in general. So neoscan homepage should work fine too

**Comment by mhuggins** [comment]
Cool, I'll update the PR.  Sounds good.
