### ISSUE TITLE
Download manager

### ISSUE THREAD

**Issue by mhuggins** [nos/client#579]
## Describe the solution you'd like and the expected behavior
Implement a download manager for downloading links/files.  Needs design.

## Is your feature request related to a problem? Please describe.
Currently, the only way to download is to right click a link and use the save dialog.  This is not tested since it's automatically included with the context menu package, and it may not even work properly.

## Possible implementation / References
N/A

## Additional context
N/A

**Comment by fabric-8** [comment]
## Download Manager Design Proposal

🖼 [Design of Figma](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=1843%3A2900)

![download manager](https://user-images.githubusercontent.com/4112698/49067583-c6a13c00-f224-11e8-8005-b5589ea37442.png)

Happy to hear your thoughts on this 😬
