### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by mhuggins** [nos/client#580]
## Describe the solution you'd like and the expected behavior
The user should be able to find text in the current page.

## Is your feature request related to a problem? Please describe.
Users can't search for text in the page.

## Possible implementation / References
* https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsfindinpagetext-options
* https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-found-in-page

## Additional context
N/A

**Comment by fabric-8** [comment]
## Find in Page Design Proposal

🕹 [Click Prototype](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=1835%3A12649&viewport=676%2C399%2C0.193539&scaling=min-zoom)
🖼 [Master Template (Overview)](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=1835%3A4230)

![kapture 2018-11-26 at 5 48 57](https://user-images.githubusercontent.com/4112698/48993628-3c32dc80-f13f-11e8-94fa-39b547ce9acd.gif)

This proposal would add a "more" menu to the browser from where the user could reach the "find in page" (as well as downloads).

Happy to hear your thoughts on this!
