### ISSUE TITLE
Address bar searches don't work for single-word searches

### ISSUE THREAD

**Issue by mhuggins** [nos/client#606]
## Expected Behavior
Type the word "test" into the address bar, and press Enter.  nOS should search for the word "test" via duckduckgo.com.

## Current Behavior
Type the word "test" into the address bar, and press Enter.  nOS navigates to http://test.

## Steps to Reproduce
1. Type the word "test" into the address bar, and press Enter.

## Possible Solution
Possibly perform a regex on the entered string to account for such cases.  Just comparing the single word to ensure it's not "localhost" is not going to be sufficient though, since the user can have any number of single-word strings in their `hosts` file.

One consideration is that we could ping the value to see if it's a host first, but this adds an extra hop and is not ideal.  I think we can find a simple string check solution.

## Additional context
We're currently using [whatwg-url](https://github.com/jsdom/whatwg-url) to parse the user's text entry.  If it's parsable as a valid URL when `http://` or `nos://` is prepended to it, then we navigate to that address.  Since `http://test` is a valid URL, navigation occurs instead of searching.

## Your Environment
* nOS Client version used: 0.4.0
* Environment name and version
  * Node version: 8.11.3
  * NPM version: 5.6.0
  * Yarn version: 1.9.4
* Operating System and version (desktop or mobile): macOS High Sierra (10.13.3)

**Comment by DalderupMaurice** [comment]
What do you think about this library to tackle this problem? https://github.com/oncletom/tld.js/
