### ISSUE TITLE
U2F / FIDO2 (Yubikey) support

### ISSUE THREAD

**Issue by mhuggins** [nos/client#607]
## Describe the solution you'd like and the expected behavior
An account locked by Yubikey (e.g.: Google) should be able to authenticate with said device.

## Is your feature request related to a problem? Please describe.
An account locked by Yubikey (e.g.: Google) is unable to authenticate with said device.  Trying to log into Google gives a notification that only Chrome can be used.

## Possible implementation / References
This is working in the Brave browser.  This implies that it's either doable because of muon (which may be using a more up to date version of Chromium), or there may be an electron interface that can be used to interface with USB devices.

It's also possible that upgrading to electron 3.x would resolve this.

## Additional context
N/A

**Comment by DalderupMaurice** [comment]
I've never even got this working in chrome when I get a popup lawl 😅 Only when I get a native prompt from the browser. That's a challenging one I think

**Comment by mhuggins** [comment]
Yes, it may be.  Although I put it under the 0.5.0 milestone, I don't think it should be a blocker for getting that version out.

**Comment by mhuggins** [comment]
Relevant issue: https://github.com/electron/electron/issues/3226  This might not be possible.
