### ISSUE TITLE
Priority fee in invocation modal

### ISSUE THREAD

**Issue by mhuggins** [nos/client#611]
## Describe the solution you'd like and the expected behavior
When the invocation modal is displayed, the user should see what the priority fee is set to and be able to change it.

## Is your feature request related to a problem? Please describe.
Priority fees are being applied, but the user may be unaware of it.  A transaction may also fail due to a low/zero fee being applied, which may be unclear.

## Possible implementation / References
![screen shot 2018-09-30 at 2 19 11 pm](https://user-images.githubusercontent.com/169093/46261619-eaadfe80-c4bb-11e8-9b1c-d50a4d4d53c6.png)

## Additional context
N/A

**Comment by DalderupMaurice** [comment]
This can be closed right? @mhuggins

**Comment by mhuggins** [comment]
@DalderupMaurice Not yet, the "change" link isn't in there yet.
