### ISSUE TITLE
Right-Click Menu in nOS browser address bar

### ISSUE THREAD

**Issue by G1ne** [nos/client#614]
## Expected Behavior

Right-click menu for address bar in nOS client browser.

When address bar is right-clicked menu should include standard options i.e Undo, Copy, Paste, Cut, Paste & Go, Select all, Delete

## Current Behavior

The address bar can select all via double-click, but currently right-click does nothing.

## Steps to Reproduce
1. Double-click in address bar
2. Hover on highlighted text and right-Click
3. Drag select text in address bar
4. Right-Click

## Possible Solution

Right-click menu addition.

## Additional context

Standard, easy address bar features.  Copy, Paste etc..

## Your Environment
* nOS Client version used: 0.4.0

* Operating System and version (desktop or mobile): Mac OSX El Capitan 10.11.6 (15G22010)

**Comment by mhuggins** [comment]
Thanks for the bug report!  I've added this to the 0.5.0 release milestone.

**Comment by G1ne** [comment]
> Thanks for the bug report! I've added this to the 0.5.0 release milestone.

No probs.  Thanks for the great work!
