### ISSUE TITLE
Upon being disconnected from the network, the nOS Client should automatically try to reconnect every x seconds

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#638]
## Describe the solution you'd like and the expected behavior
Upon being disconnected from the network, the nOS Client should automatically try to reconnect every x seconds

## Is your feature request related to a problem? Please describe.
You have to go to settings select another network and reselect the previous network to be able to reconnect to the network.

## Possible implementation / References
/

## Additional context
/

**Comment by mhuggins** [comment]
Duplicate of #554.
