### ISSUE TITLE
Auto-updates

### ISSUE THREAD

**Issue by deanpress** [nos/client#720]
## Describe the solution you'd like and the expected behavior
nOS Client should auto-update on start.

**Comment by DalderupMaurice** [comment]
I'll mark this as blocked. We'll have to implement #476 first

**Comment by mhuggins** [comment]
Whether using an third party service or a custom update server, we'll want something that support Yubikey login to ensure that only nOS members can access for supplying updates.

**Comment by jeroenptrs** [comment]
https://www.dblsqd.com/go/electron

**Comment by mhuggins** [comment]
Looks like dblsqd.com won't work.  During sign-up, I got this 500 error telling me to email them:

<img width="452" alt="500-error" src="https://user-images.githubusercontent.com/169093/49701360-0961fd00-fbb1-11e8-8e93-4274339ec285.png">

Then when I emailed them, I got a mailer daemon response:

<img width="813" alt="mailer-daemon" src="https://user-images.githubusercontent.com/169093/49701365-1ed72700-fbb1-11e8-9e52-ff343ef2ec6c.png">

**Comment by DalderupMaurice** [comment]
https://www.electron.build/configuration/publish

Seems like we can use the builtin auto-updated from electron-builder
It also supports [BinTray](https://bintray.com/account/pricing?tab=account&type=pricing) which is free for open source projects, so we don't need an AWS S3 or something. Last resort - it's also possible to use github as a "host" for the releases
cc @mhuggins
