### ISSUE TITLE
Log-in to nOS Client should be optional (no log-in screen on start-up)

### ISSUE THREAD

**Issue by deanpress** [nos/client#721]
## Describe the solution you'd like and the expected behavior
Users should be able to use nOS Client without being logged in to any account. Logging in to an account should be a feature inside nOS Client instead of a separate window.

**Comment by Marcpepe** [comment]
Also, there should be a way to remember one's credentials, instead of always having to re-login every time nos client is launched.

**Comment by DalderupMaurice** [comment]
You don't have an option to stay signed in with your banking application. I think this applies to the nOS Client aswell
