### ISSUE TITLE
Reactify webview

### ISSUE THREAD

**Issue by mhuggins** [nos/client#8]
https://github.com/MarshallOfSound/react-electron-web-view

**Comment by DalderupMaurice** [comment]
What's the status on this? -IF we process with electron at all 😄 @mhuggins

**Comment by mhuggins** [comment]
@DalderupMaurice That's not a new version, that's from a year ago.  We can just close this for now.  It was a tiny nice-to-have, but not really necessary.

**Comment by DalderupMaurice** [comment]
Thought it was 2018 😂 Only looked at the day-months hahahaha
