### ISSUE TITLE
View-icons (eyes) on the "Activies" page lead to 404s.

### ISSUE THREAD

**Issue by jean-acsas** [nos/client#808]
## Expected Behavior
View-Icon (eye) on the Activies page should lead me to the appropriate Activity page.

## Current Behavior
Clicking one of the eye-icons the link leads to a 404 (page not found). Especially for active Activies that's problematic. The actual link to the activity on the left side of the table works.

## Steps to Reproduce (for bugs)
1. Start nOS-Client.
2. Go to Activities Page.
3. Click on any of the eye-icons (that should lead to the overview of the activity.  
4. Be confronted with a 404.

## Possible Solution
1. Assign the proper link of the specific activity to the icon/eye it refers to, or correct the logic that does the assignment.
2. Gray out the icon in the meantime.
  

## Additional context
I wanted to have a look what the activity entails. The eye-icon naturally caused my attention.

## Your Environment
* nOS Client version used: 0.4.6
* Environment name and version
    * Node version: 8.10.0
    * NPM version: 3.5.2
    * Yarn version: 1.12.3
* Operating System and version (desktop or mobile):
Ubuntu 18.04

**Comment by deanpress** [comment]
Fixed, thank you!
