### ISSUE TITLE
Change `getBalance` to take an address

### ISSUE THREAD

**Issue by mhuggins** [nos/client#82]
We currently have `getBalance` in our API, which takes an asset ID or NEP5 script hash as an argument and retrieves the current account's balance for that asset/token.

I suggest we change this function to take two arguments, with the first argument being the address that we should fetch the balance for.  This would make it more extensive in case another address balance is needed, and it could still work smoothly with the way our API works, e.g.:

```js
nos.getAddress()
  .then((address) => nos.getBalance(address, NEO))
  .then((balance) => console.log(balance))
  .catch((err) => console.log(err.message));
```

**Comment by jeroenptrs** [comment]
That's pretty good, let's open up a branch
