### ISSUE TITLE
Add additional neoscan URLs in Network Settings

### ISSUE THREAD

**Issue by deanpress** [nos/client#86]
Currently users can only select networks from a set of predetermined neoscan URLs. We should let users add custom ones.

**Comment by robmoorman** [comment]
Entering an invalid url is your own responsibility I would say. Keeping up your (custom) list in Redux would be the way to go. Maybe prefill (as initial state) this with the ones currently hardcoded.

**Comment by kitchenSpoon** [comment]
Thanks @robmoorman , would asking for a name and a neoscan address, like in this page be enough?
http://cityofzion.io/neon-js/docs/en/basic_privnet.html

**Comment by kitchenSpoon** [comment]
Is there anything else that needs to be done to move this from In progress to Done?
