### ISSUE TITLE
Read-only API access to nOS client settings

### ISSUE THREAD

**Issue by hal0x2328** [nos/client#870]
## Describe the solution you'd like and the expected behavior
nOS client settings (currency locale, current network, minimum fee) exposed via the API for dApps to read.

## Is your feature request related to a problem? Please describe.
The dApp I'm writing has a different contract hash on MainNet vs TestNet, but there's no simple way for it to determine which one is actively connected in the nOS client without a kludgy workaround like invoking each hash to see which one responds.

**Comment by DalderupMaurice** [comment]
Created a PR for this issue. 
Although "fees" won't be included until we've added support for multiple blockchains as that might be changed/moved around.
