### ISSUE TITLE
Attach assets to invocations

### ISSUE THREAD

**Issue by deanpress** [nos/client#88]
We should let users attach assets to invocations so they can run VerificationTransaction methods in their smart contract (accept payments with invocations).

**Comment by DalderupMaurice** [comment]
Could you clarify this issue more, please? @deanpress

**Comment by jeroenptrs** [comment]
@DalderupMaurice likewise, this seems a bit more complex and fit for a team issue

**Comment by syedasifraza** [comment]
@DalderupMaurice @jeroenptrs 
Any expected date to finish this issue?
