### ISSUE TITLE
Double Clicking on the nOS Client Outputs Console Error

### ISSUE THREAD

**Issue by philiparthurmoore** [nos/client#99]
When I double click on the background of Electron, I receive the following console warning:

```
2018-04-25 01:56:51.800 Electron Helper[23856:11781545] Couldn't set selectedTextBackgroundColor from default ()
```

Steps to reproduce:

1. `yarn start`
2. Double click on the pink/blue gradient background of Electron.

<img width="731" alt="2018-04-25_01-58-52" src="https://user-images.githubusercontent.com/28684/39208130-3c1ad282-482c-11e8-98c8-f59f189850af.png">

**Comment by mhuggins** [comment]
For all intents and purposes, I believe this is more or less a non-issue.  https://github.com/electron/electron/issues/4420

**Comment by philiparthurmoore** [comment]
I'm closing this. Good find on the related issue. Thanks!
